import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-white">
          <div className="mx-auto grid max-w-2xl grid-cols-1 items-center gap-y-16 gap-x-8 py-24 px-4 sm:px-6 sm:py-32 lg:max-w-7xl lg:grid-cols-2 lg:px-8">
            <div className='max-w-sm mb-32'>
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Smarten up your work look or throw on a blazer with jeans for the weekend</h2>
              <button className='bg-black hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mt-4'>
                <div className='flex'>
                  <p>Shop Now </p>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6 ml-2">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                  </svg>
                </div>
              </button>
              <img  className="mt-8"></img>
            </div>
            <div className="">
              <img  className="w-full h-screen"></img>
              <h2 className="text-sm tracking-tight text-gray-900 sm:text-4xl">At suspendisse augue lectus arcu, accumsan ut sit posuere vitae sit tincidunt semper eu proin leo gravida cursus.</h2>
              <button className='bg-black hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mt-4'>
                <div className='flex'>
                  <p>Shop Now </p>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6 ml-2">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                  </svg>
                </div>
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
