import Head from 'next/head'
import { Inter } from '@next/font/google'
import source from '../image/image.jpg' 
import sourceOther from '../image/image1.jpg' 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='flex flex-row max-w-lg ml-16 mt-16'>
          <h2 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-4xl mb-8 ml-8" style={{fontFamily: 'Avenir' }}>Smarten up your work look or throw on a blazer with jeans for the weekend</h2>
        </div>
        <div className='flex flex-row ml-16'>
          <button className='bg-black hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mt-4 m-8'>
            <div className='flex'>
              <p style={{fontFamily: 'Avenir' }}>Shop Now </p>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6 ml-2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
              </svg>
            </div>
          </button> 
        </div>
        <div className='flex flex-row lg:w-full lg:h-screen ml-16'>
          <img src={source.src} ></img>
          <img src={sourceOther.src} className="ml-20 w-2/5 lg:absolute lg:top-10 lg:w-2/5 lg:right-16 lg:h-full "></img>
          <div className="lg:w-1/2 relative w-1/2 right-3/4 lg:left-64 ">
            <div className="flex justify-center absolute top-3/4 w-3/5 lg:absolute  lg:top-1/2 lg:w-3/5">
              <div className="flex flex-col h-20 rounded-lg bg-white shadow-lg lg:flex-row lg:w-3/4">
                <div className="hidden lg:p-6 lg:flex lg:flex-col lg:justify-start">
                  <h5 className="text-gray-900 text-sm font-medium ">Saffiano Leather Bag 2005</h5>
                  <p className="text-gray-600 text-xs">€ 199.95</p>
                </div>
                <img className="w-full h-20 p-2 mr-16 object-cover lg:w-16 lg:h-20 lg:m-0" src="https://mdbootstrap.com/wp-content/uploads/2020/06/vertical.jpg" alt="" />
              </div>
            </div>
          </div>
        </div>
        <div className='float-right lg:w-2/5 h-64 m-16 lg:absolute lg:top-full lg:w-2/5 lg:right-1 lg:h-5/6'>
          <div className='flex flex-row'>
            <h2 className="text-lg tracking-tight text-gray-900" style={{fontFamily: 'Avenir' }}>At suspendisse augue lectus arcu, accumsan ut sit posuere vitae sit tincidunt semper eu proin leo gravida cursus.</h2>
          </div>
          <div className='flex flex-row'>
            <p className='underline underline-offset-8 cursor-pointer mt-8' style={{fontFamily: 'Avenir' }}>Read More </p>
          </div>
        </div>
      </main>
    </>
  )
}
